service: aws-xray-lambda

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 256
  apiKeys:
    - tracingApiKey
  environment:
    API_KEY: '${file(secrets.yml):API_KEY}'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
        - "lambda:InvokeFunction"
      Resource: "*"
# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  include:
    - node_modules/co/**
    - node_modules/bluebird/**
    - node_modules/lodash/**
    - node_modules/request/**
    - node_modules/request-promise/**
    - node_modules/aws-xray-sdk-core/**
  exclude:
    - node_modules/**
    - secrets.yml

functions:
  a:
    handler: functions/a.handle
    events:
      - http:
          path: a
          method: post
          private: true
  b:
    handler: functions/b.handle
  c:
    handler: functions/c.handle
    events:
      - http:
          path: c
          method: post
          private: true

resources:
  Resources:
    tracingTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        TableName: "tracingTable"
        AttributeDefinitions: 
          - 
            AttributeName: "key"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "key"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
